Completed Student Registration, Fetching Students, and Fetching StudentById
miu-test/annapurna-be pull request #1
Opened 2022-06-25 03:25 UTC by bijay-shrestha

Completed all three APIs.

2022-06-26 03:59 UTC, shellyneira requested changes

2022-06-26 03:59 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +        StudentResponseDTO studentResponseDTO = studentService.registerStudent(studentRequestDTO);
here we do not need the variable studentResponseDTO, you can just make the student registration

2022-06-26 03:59 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/service/StudentService.java
> +import edu.miu.annapurnabe.model.Student;
import not used

2022-06-26 03:59 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +
white space xD

2022-06-26 03:59 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/model/Student.java
> +import lombok.AllArgsConstructor;
import not used, some white spaces between imports.

2022-06-26 03:59 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/configuration/StudentStarterConfig.java
> +public class StudentStarterConfig {
Hmm, for populating zero-data db I would prefer using another approach, for example using a local script instead implementing it on code, once our application have its first day of use, this code feature won't be used, so we should make it keep clean =).

Another point is, our org emails are being shared here, for security reasons we need to take care about these sensitive data.

2022-06-26 03:59 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/dto/request/StudentRequestDTO.java
> +
white space xD

2022-06-26 03:59 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/dto/request/StudentRequestDTO.java
> +    private LocalDate dob;
I was able to guess what 'dob' ​​means after looking at its object, i'd rather use dateOfBirth.

The usage of Intention-Revealing Names is important for a clean code x)

2022-06-26 03:59 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/dto/response/StudentResponseDTO.java
> +
White space

2022-06-26 03:59 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/repository/StudentRepository.java
> +
White Space

2022-06-26 03:59 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +
White space

2022-06-26 03:59 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +                studentRequest.getPassword().toCharArray()));
I couldn't find the method getPassword() in Student class

2022-06-26 03:59 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +        existingStudent.setFullName(toBeUpdatedStudent.getFullName());
The methods setStatus(), getFullName(), getEmail(), getDob(), getStatus() and isSubscribed() are missing in Student class.

2022-06-26 14:02 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +    public ResponseEntity<?> getStudentById(@PathVariable("studentId") Long id){
Actually 'Long' is preferred than "Integer' shelly. As int is 32 bits and long is 64 :)

2022-06-26 14:04 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +import edu.miu.annapurnabe.model.Student;
it has usage :)

2022-06-26 14:05 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +        StudentResponseDTO studentResponseDTO = studentService.registerStudent(studentRequestDTO);
Shelly, actually for data transfer, it is recommended to use Data Transfer Objects rather than entity class. Plus, for addition it is not really necessary to send the response but then it really depends on the API design :)

2022-06-26 14:05 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +
taken care of :)

2022-06-26 14:06 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/service/StudentService.java
> +import edu.miu.annapurnabe.model.Student;
taken care of :)

2022-06-26 14:07 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/dto/response/StudentResponseDTO.java
> +
taken care :)

2022-06-26 14:07 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/repository/StudentRepository.java
> +
taken care ;)

2022-06-26 14:07 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +
taken care of ;)

2022-06-26 14:08 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +                studentRequest.getPassword().toCharArray()));
actually Lombok's '@Data' annotation provides it so you don't see them shelly!

2022-06-26 14:09 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +        existingStudent.setFullName(toBeUpdatedStudent.getFullName());
Shelly, student class has @Data, it provides getters and setters so we don't need them to be defined implicitly XD

2022-06-26 14:23 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +        existingStudent.setFullName(toBeUpdatedStudent.getFullName());
I don't know why @Data became @DaTa .. tf!

2022-06-26 14:37 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +    public ResponseEntity<?> getStudentById(@PathVariable("studentId") Long id){
Yeah, I know, I mean we don't need use a longer data type since we won't ever reach all the capacity on an int, if we think about this project.

2022-06-26 14:41 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +        StudentResponseDTO studentResponseDTO = studentService.registerStudent(studentRequestDTO);
I meant the variable 'studentResponseDTO' is not being used.
`Compiler Warning: The value of the local variable studentResponseDTO is not usedJava(536870973)
`
So we can remove the code `'StudentResponseDTO studentResponseDTO'` to don't allocate memory unnecessarily.

2022-06-26 15:35 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +                studentRequest.getPassword().toCharArray()));
Got it! I didn't know this library. Even using it, it still showing compile errors, however I was able to run it.

2022-06-26 15:36 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +                studentRequest.getPassword().toCharArray()));
Got it! I didn't know this library. Even using it, it still showing compile errors

2022-06-26 15:41 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +        existingStudent.setFullName(toBeUpdatedStudent.getFullName());
Do you meant @Data?

2022-06-26 15:41 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +        existingStudent.setFullName(toBeUpdatedStudent.getFullName());
`@Data` XD

2022-06-26 15:44 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +import edu.miu.annapurnabe.model.Student;
<img width="481" alt="Screen Shot 2022-06-26 at 10 42 36 AM" src="https://user-images.githubusercontent.com/59582480/175822258-2f151474-9ed4-40fb-b4bf-1e4eb82bd83a.png">

Do you meant the same line as me?

2022-06-26 17:11 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +        StudentResponseDTO studentResponseDTO = studentService.registerStudent(studentRequestDTO);
oh shoot! .. I meant to send the dto as response ... my bad!! will fix it ;)

2022-06-26 17:12 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +import edu.miu.annapurnabe.model.Student;
oh! I removed... 'Student'. I thought the whole bunch were not under use

2022-06-26 17:13 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +    public ResponseEntity<?> getStudentById(@PathVariable("studentId") Long id){
.. haha... I guess we'll be safe if we put long .. but if you want me to change to integer .. I'm cool !

2022-06-26 17:36 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +    public ResponseEntity<?> registerStudent(@RequestBody StudentRequestDTO studentRequestDTO) throws URISyntaxException {
Fixed Shelly!

2022-06-26 17:36 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +        StudentResponseDTO studentResponseDTO = studentService.registerStudent(studentRequestDTO);
Fixed!

2022-06-26 17:37 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +        existingStudent.setFullName(toBeUpdatedStudent.getFullName());
`@Data`

2022-06-26 17:37 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +                studentRequest.getPassword().toCharArray()));
did you do `mvn clean package`

2022-06-26 17:44 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +    public ResponseEntity<?> getStudentById(@PathVariable("studentId") Long id){
Changed Datatype from Long to Integer XD and reflected in other APIs. Tested as well!

2022-06-26 18:36 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +        student.setStatus('D');
What means 'D'?

2022-06-26 18:39 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +        student.setStatus('D');
So, D means 'Delete', we can have 'B' for Blocked, 'I' for inactive students. It's merely a change of students.. so when we delete a student we do not delete the whole data, we'd simply change the status.

2022-06-26 19:04 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +        student.setStatus('D');
Noiiice! what do u think to assign the 'D' char to an const named Disable? it seems give more meaning to the code.

2022-06-26 20:24 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +        student.setStatus('D');
@shellyneira , Done ;)

2022-06-26 21:11 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/dto/request/StudentRequestDTO.java
> +
done!

2022-06-26 21:11 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/dto/request/StudentRequestDTO.java
> +    private LocalDate dob;
taken care of!

2022-06-26 21:11 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/model/Student.java
> +import lombok.AllArgsConstructor;
taken care!

2022-06-26 21:13 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/configuration/StudentStarterConfig.java
> +public class StudentStarterConfig {
the starter config will be used to create a super user and will execute only once. I have a better way of doing this. Not to worry, we're at the initial stage of development, these code will be polished overtime XD

2022-06-27 01:37 UTC, shellyneira requested changes

2022-06-27 01:37 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/constant/StringConstant.java
> +public class StringConstant {
Putting a const inside an interface it's considered a bad practice, Constant Interface Anti-pattern (source: Effective Java: Programming Language Guide)

StringConstant is a generic name, we should use a class just for the student state. I understand the 'delete' but maybe 'disable' makes more sense in the context. What do you think? 

```
public final class StudentStateConstants { 

           public static final Character DISABLE = 'D'; 
}
```
Feel free to review my code as well xd

2022-06-27 02:50 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/constant/StringConstant.java
> +public class StringConstant {
Oh, it's good! I didn't know that. ;) And making the class absolutely immutable is also the best practice. Kudos!

2022-06-27 02:57 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/constant/StringConstant.java
> +public class StringConstant {
I made the changes shelly. But instead of specifying the class as 'StudentStateConstant' I've named it StatusConstant as we this will make the class re-usable. ;)

2022-06-27 15:15 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/constant/BooleanConstant.java
> +public final class BooleanConstant {
Why this constant was created? `false` is self-explainable. Setting `student.setSubscribed(false);` is not a bad practice

2022-06-27 15:15 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/constant/StringConstant.java
> +public class StringConstant {
Do you think will we use this status in a short-time? Our project it's close to the end, so now we have a better vision to what we could use/not use and embrace YAGNI principle. We also must take care if we think in reuse it, to don't violate LSP. Generalize this class may be not the best option

2022-06-27 15:16 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/configuration/StudentStarterConfig.java
> +public class StudentStarterConfig {
Anyways, I care about security reasons xD

2022-06-27 15:20 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/constant/StringConstant.java
> +public class StringConstant {
Do you think will we use this status in a short-time? Our project it's close to the end, so now we have a better vision to what we could use/not use and embrace YAGNI principle. We also must take care if we think in reuse it, to don't violate LSP. Generalize this class may be not the best option

2022-06-27 15:39 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/constant/StringConstant.java
> +public class StringConstant {
I think we can leave that for Open for Extension and Closed for Modification. ;)
For example we need them when we do crud for admin setup or say in the future faculty registration.

2022-06-27 16:22 UTC, shellyneira requested changes

2022-06-27 16:22 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/constant/BooleanConstant.java
> +public final class BooleanConstant {
When we want to reuse code, it need to have a motivation behind that will really make our code better, like: Improve the performance, reduce code repetition, to be easier to maintain in future, etc. In this case, I think better presentation is not ideal reason in this case.
I can see one advantage there, every time we receive a request and invoke the stack, it'll get this constant boolean state, that its intangible since is static instead re-create and instantiate like if we put directly `true` `false`. This would be a good reason, but the performance will not improve in a way we can feel. Anyways, it seems don't worth this modification. What do you think?

2022-06-27 16:28 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/constant/StringConstant.java
> +public class StringConstant {
YAGNI principle is 100% legit. So yes, we'd rather generalize when we need them. Thus, for now I renamed the class name back to StudentStatusConstant. ;)

2022-06-27 16:32 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/constant/StringConstant.java
> +public class StringConstant {
Great, there is something we're definitely use. So the person has a state. What do you think to move this state constant and the disable() function into a Person class with subclasses Faculty and Student (when we implements Faculty, in another PR)?
I was thinking in another ways but i think it will be over engineering...

2022-06-27 16:34 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/constant/StringConstant.java
> +public class StringConstant {
oh, for sure it will be an over engineering if we did so

2022-06-27 17:06 UTC, shellyneira requested changes

2022-06-27 17:06 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +    public StudentResponseDTO registerStudent(StudentRequestDTO studentRequestDTO) {
I think every time we create a student, we should set it as active by default, once only admins can access this endpoint, right? So it would be less one parameter to we set sending requests.

2022-06-27 17:06 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +    public StudentResponseDTO registerStudent(StudentRequestDTO studentRequestDTO) {
If we have only two status, like 'Y' / 'D' we could use bool instead char. it can improve db performance when we search registers by bool over chars.

2022-06-27 17:13 UTC, shellyneira requested changes

2022-06-27 17:13 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/repository/StudentRepository.java
> +
change to Integer to avoid unnecessary casting

2022-06-27 17:21 UTC, shellyneira requested changes

2022-06-27 17:21 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +    public ResponseEntity<?> getStudentById(@PathVariable("studentId") Integer id){
Here we already make use of the `import StudentResponseDTO`, then why using wildcards '?' to erase type instead `ResponseEntity<StudentResponseDTO>` ?

2022-06-27 18:42 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/repository/StudentRepository.java
> +
that was a big mistake. thanks for pointing that out. I refactored everybit of long to integer but forgot this little guy here

2022-06-27 18:44 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/service/impl/StudentServiceImpl.java
> +    public StudentResponseDTO registerStudent(StudentRequestDTO studentRequestDTO) {
that make sense at this point but when student would login multiple times with wrong credentials we'd have to block him/her. For that use case I used char

2022-06-27 19:02 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +    public ResponseEntity<?> getStudentById(@PathVariable("studentId") Integer id){
Could you please share the source of this affirmation? 

> The wildcard can be used in a variety of situations: as the type of a parameter, field, or local variable; sometimes as a return type (though it is better programming practice to be more specific)
Source: https://docs.oracle.com/javase/tutorial/java/generics/wildcards.html

2022-06-27 19:10 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +    public ResponseEntity<?> getStudentById(@PathVariable("studentId") Integer id){
Using wildcards (erased type) has some behaviors we should mind, specially when we compare to a typed one in its compile time and runtime behavior.

2022-06-27 19:14 UTC, bijay-shrestha commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +    public ResponseEntity<?> getStudentById(@PathVariable("studentId") Integer id){
shelly, sorry for the confusion. Generics/Wildcards were preferred to increase the API flexibility but I realized it wasn't the best use case in the Rest Controllers when we have a specified return type. I even edited my message up there XD but you must have seen it before I edited them. xP

2022-06-27 19:19 UTC, shellyneira commented on src/main/java/edu/miu/annapurnabe/api/StudentResource.java
> +    public ResponseEntity<?> getStudentById(@PathVariable("studentId") Integer id){
Great =) 
So, in this case wildcards don't have its benefits being used once we only expect one type of response always

2022-06-27 20:58 UTC, shellyneira approved these changes

2022-06-28 17:00 UTC, merged